# Generated by Django 3.0.5 on 2020-05-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='Choice_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cards',
            name='Choice_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cards',
            name='Choice_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cards',
            name='Choice_d',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Choicess',
        ),
    ]
