# Generated by Django 3.0.5 on 2020-05-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_auto_20200512_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='Choice_a',
            new_name='choice_a',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Choice_b',
            new_name='choice_b',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Choice_c',
            new_name='choice_c',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='Choice_d',
            new_name='choice_d',
        ),
    ]
