# Generated by Django 3.0.5 on 2020-05-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0003_auto_20200512_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='choice_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cards',
            name='choice_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cards',
            name='choice_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cards',
            name='choice_d',
            field=models.CharField(max_length=200),
        ),
    ]
