# Generated by Django 3.0.5 on 2020-05-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0004_auto_20200512_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='choice_d',
        ),
    ]
