# Generated by Django 3.0.5 on 2020-05-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0005_remove_cards_choice_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='choice_c',
        ),
    ]
